### ISSUE TITLE
莱特兰部分武器无法正确打上标签

### ISSUE THREAD

**Issue by shenyx110** [MCTeamPotato/Unbreakabler#1]
https://github.com/Minecraft-LightLand/L2Weaponry
如幽匿弯刀 海神标枪

**Comment by Kasualix** [comment]
原版指令可行否？/give @p l2weaponry:sculkium_machete{Unbreakable:1} 1

**Comment by shenyx110** [comment]
原版指令可行

**Comment by Kasualix** [comment]
没研究出来，你可能得去问问L2W他们哪儿怎么搞的不兼容了

**Comment by lcy0x1** [comment]
我有自己的inventoryTick，没调用Item的。我这里可以处理兼容，但是还是建议你们在ItemStack里面而不是Item里面加Mixin
