### ISSUE TITLE
最新版本无法识别

### ISSUE THREAD

**Issue by shenyx110** [MCTeamPotato/Unbreakabler#3]
最新版本无法识别 
<img width="885" alt="截屏2023-06-02 13 14 25" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/3fb1b257-f0a6-4559-b39b-2754db5d2285">
<img width="885" alt="截屏2023-06-02 13 13 06" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/e238aaba-120d-4106-adcc-8702bee26ca3">
<img width="885" alt="截屏2023-06-02 13 12 58" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/3fc5f157-aa4c-4947-81fa-4d13fc35cf97">
<img width="885" alt="截屏2023-06-02 13 12 39" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/2efaca8b-a701-45d7-b49c-816448640448">
[minecraft-exported-logs-2023-06-02T13-13-09.log](https://github.com/MCTeamPotato/Unbreakabler/files/11632059/minecraft-exported-logs-2023-06-02T13-13-09.log)
并且会导致所有模组文件失效

**Comment by shenyx110** [comment]
<img width="922" alt="截屏2023-06-02 13 19 02" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/72bc2439-1599-4321-954b-f42f17b0872f">
s
<img width="922" alt="截屏2023-06-02 13 19 32" src="https://github.com/MCTeamPotato/Unbreakabler/assets/132644153/db768a30-8102-43a2-85ca-fff8fffab461">
上一版本正常加载

**Comment by Kasualix** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/unbreakabler/files/4563325
