### ISSUE TITLE
已更新最新版本 双击湿海绵时崩溃

### ISSUE THREAD

**Issue by shenyx110** [MCTeamPotato/Unbreakabler#5]
[minecraft-exported-logs-2023-06-03T18-49-08.log](https://github.com/MCTeamPotato/Unbreakabler/files/11642404/minecraft-exported-logs-2023-06-03T18-49-08.log)

**Comment by shenyx110** [comment]
不过可能好像不是源于这个

**Comment by Kasualix** [comment]
> 不过可能好像不是源于这个

我也觉得

**Comment by Kasualix** [comment]
你这崩的是客户端渲染，但unbreakabler所有的逻辑都是在服务端运作的

**Comment by Kasualix** [comment]
not enough crashes 删掉再发一次崩溃报告看看？我听说这玩意偶尔会把崩溃报告给弄坏掉，无法显示真正的崩溃原因

**Comment by shenyx110** [comment]
我感觉好像和那个通用附魔UniversalEnchants有关 我再去那边也提交一下

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Unbreakabler/assets/110756250/e844c00e-7033-4d54-a20c-b6313bf36756)
会不会跟暮色森林的渲染有关系？要不要删掉试试？
它这个渲染是可以用数据包自定义的，在[data/twilightforests/dimension_type](https://github.com/TeamTwilight/twilightforest/blob/bfc148a8c1183938f0061852582ae9dd24836501/src/generated/resources/data/twilightforest/dimension_type/twilight_forest_type.json#L5)里，把那行"effects": "twilightforest:renderer"删掉就行

**Comment by shenyx110** [comment]
[minecraft-exported-logs-2023-06-03T19-07-15.log](https://github.com/MCTeamPotato/Unbreakabler/files/11642426/minecraft-exported-logs-2023-06-03T19-07-15.log)
[minecraft-exported-crash-info-2023-06-03T19-07-07.zip](https://github.com/MCTeamPotato/Unbreakabler/files/11642427/minecraft-exported-crash-info-2023-06-03T19-07-07.zip)

好像找到问题了
有多组海绵
其中有一组被打了标签
只要放置或者尝试堆叠会直接崩溃

**Comment by Kasualix** [comment]
![image](https://github.com/MCTeamPotato/Unbreakabler/assets/110756250/6065a8ad-3495-4342-b624-4f4f098a399d)
我更怀疑是你这物品编辑器的问题（？

**Comment by shenyx110** [comment]
我刚刚尝试用编辑器想看看是什么但是不会用QAQ
打开了界面然后就关闭了没有操作
随后尝试放置物品直接黑了

**Comment by shenyx110** [comment]
暮色的渲染应该只在那个维度生效？（我不太懂）
我这个问题是在主世界的
删除了渲染还是同样的方法复现bug
只要放那个海绵就出问题 错误应该就定位在这里了
（但是上次放的海绵居然还在 所以每崩溃一次可以放一块bushi）
[minecraft-exported-crash-info-2023-06-03T19-28-08.zip](https://github.com/MCTeamPotato/Unbreakabler/files/11642476/minecraft-exported-crash-info-2023-06-03T19-28-08.zip)
[minecraft-exported-logs-2023-06-03T19-28-05.log](https://github.com/MCTeamPotato/Unbreakabler/files/11642477/minecraft-exported-logs-2023-06-03T19-28-05.log)

**Comment by Kasualix** [comment]
光影&oculus？

**Comment by shenyx110** [comment]
[minecraft-exported-crash-info-2023-06-03T20-11-22.zip](https://github.com/MCTeamPotato/Unbreakabler/files/11642586/minecraft-exported-crash-info-2023-06-03T20-11-22.zip)
[minecraft-exported-logs-2023-06-03T20-11-15.log](https://github.com/MCTeamPotato/Unbreakabler/files/11642587/minecraft-exported-logs-2023-06-03T20-11-15.log)
关了 
这次鼠标碰到物品栏里海绵就炸了QAQ

**Comment by Kasualix** [comment]
既然是海绵，是不是可以怀疑一下biggerspongeabsorptionradius-1.19.4-3.1.jar？
